[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin=lib/openzeppelin-contracts']


[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/<YOUR_PROJECT_ID>"
mumbai = "https://polygon-mumbai.infura.io/v3/<YOUR_PROJECT_ID>"
amoy = "https://rpc-amoy.polygon.technology"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
